name: CI/CD Demo

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      # - name: Run PHP test
      #   run: php backend/*.php

      # -----------------------
      # BACKEND (PHP) TESTS
      # -----------------------
      - name: Install Composer dependencies
        working-directory: ./backend
        run: composer install --no-interaction

      - name: Run PHPUnit tests
        working-directory: ./backend
        run: php vendor/bin/phpunit

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install frontend dependencies
        run: npm install
        working-directory: ./frontend/vite-project

      - name: Run React frontend tests
        run: npx jest
        working-directory: ./frontend/vite-project

      - name: Build React frontend
        run: npm run build
        working-directory: ./frontend/vite-project
